#image: docker:latest
#services:
#  - docker:dind

#variables:
#  DOCKER_DRIVER: overlay2

#stages:
#  - build
#  - deploy
  
#docker-build:
#  stage: build
#  script:
#  - docker login -u $CI_ACCESS_USER -p $CI_ACCESS_TOKEN registry.gitlab.com
#  - docker build -f Dockerfile --iidfile imageid.txt -t registry.gitlab.com/dk-java-humans-vs-zombies/humans-vs-zombies.backend .
#  - docker push registry.gitlab.com/dk-java-humans-vs-zombies/humans-vs-zombies.backend:latest

#heroku-deploy:
#  stage: deploy
#  services:
#   - docker:dind
#  script:
#    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
#    - docker pull registry.gitlab.com/dk-java-humans-vs-zombies/humans-vs-zombies.backend:latest
#    - docker tag registry.gitlab.com/dk-java-humans-vs-zombies/humans-vs-zombies.backend:latest registry.heroku.com/dk-hvz-backend:latest
#    - docker push registry.heroku.com/dk-hvz-backend:latest
#    - docker run --rm -e HEROKU_API_KEY=$HEROKU_TOKEN wingrunr21/alpine-heroku-cli container:release web --app dk-hvz-backend
